import Foundation
import Observation
import AppKit

enum OllamaStatus: Equatable {
    case unknown
    case connected(String)
    case unreachable(String)

    var isConnected: Bool { if case .connected = self { return true } else { return false } }
}

enum ApprovalDecision {
    case allow, allowAll, deny
}

/// Why the sidebar is asking for a new group name.
struct NewGroupRequest: Identifiable, Hashable {
    var id = UUID()
    /// Chat to move into the group once it exists, if any.
    var conversationID: UUID?
}

@MainActor
@Observable
final class AppModel {
    var conversations: [Conversation] = []
    var selectedID: Conversation.ID?
    var groups: [ChatGroup] = []
    /// Chats whose name is being generated by the model right now.
    var generatingTitleIDs: Set<UUID> = []
    /// Set to ask the sidebar to show the "new group" prompt (optionally moving a chat into it).
    var newGroupRequest: NewGroupRequest?
    var models: [OllamaModelInfo] = []
    var runningModels: [RunningModel] = []
    var modelStats: [String: ModelStats] = [:]
    var loadingStats: Set<String> = []
    var status: OllamaStatus = .unknown
    var isGenerating = false
    var pendingApprovalID: UUID?
    var showModelsSheet = false
    var isPulling = false
    var pullingName = ""
    var pullProgress: PullProgress?
    var pullError: String?
    var errorBanner: String?
    var isStartingOllama = false
    /// Sidebar search. Filters the chat list and highlights matching messages.
    var searchQuery = ""
    /// Bumped by ⌘F so the sidebar can move focus to the search field.
    var searchFocusRequest = 0

    let settings = AppSettings()
    let approvals = ApprovalRules()
    let tor = TorManager()
    /// Whether the configured HTTP/SOCKS proxy answers on its port (nil when not applicable).
    var proxyReachable: Bool?
    var isCheckingConnection = false
    /// Result of the last "Test connection": exit IP and route.
    var connectionResult: String?
    var lastExitIP: String?
    /// "Allow all this session" was chosen for a tool approval.
    var allowAllThisSession = false
    /// Incremented after every tool run; views use it to re-check files the model mentions.
    var toolRunCount = 0

    private let store = ConversationStore()
    private var generationTask: Task<Void, Never>?
    private var pullTask: Task<Void, Never>?
    private var approvalContinuation: CheckedContinuation<ApprovalDecision, Never>?
    private var modelsWithoutTools: Set<String> = []

    private var client: OllamaClient { OllamaClient(baseURL: settings.hostURL) }

    // MARK: - Disclosure state

    // Expand/collapse state for chat detail sections (tool results, thinking), keyed by a
    // stable id so it survives the lazy list recycling rows during scroll or streaming.
    private var detailOpen: Set<UUID> = []
    private var detailClosed: Set<UUID> = []

    func isDetailExpanded(_ id: UUID, default def: Bool) -> Bool {
        if detailOpen.contains(id) { return true }
        if detailClosed.contains(id) { return false }
        return def
    }

    func toggleDetail(_ id: UUID, default def: Bool) {
        if isDetailExpanded(id, default: def) {
            detailClosed.insert(id); detailOpen.remove(id)
        } else {
            detailOpen.insert(id); detailClosed.remove(id)
        }
    }

    // MARK: - Selection helpers

    var selected: Conversation? {
        get { conversations.first { $0.id == selectedID } }
        set {
            guard let newValue, let idx = conversations.firstIndex(where: { $0.id == newValue.id }) else { return }
            conversations[idx] = newValue
        }
    }

    var sortedConversations: [Conversation] {
        conversations.sorted { $0.updatedAt > $1.updatedAt }
    }

    // MARK: - Search

    var trimmedSearchQuery: String { searchQuery.trimmingCharacters(in: .whitespacesAndNewlines) }
    var isSearching: Bool { !trimmedSearchQuery.isEmpty }

    func messageMatches(_ message: ChatMessage) -> Bool {
        let q = trimmedSearchQuery
        guard !q.isEmpty, message.role == .user || message.role == .assistant else { return false }
        if message.content.localizedCaseInsensitiveContains(q) { return true }
        return message.attachments.contains { $0.fileName.localizedCaseInsensitiveContains(q) }
    }

    func searchMatches(in convo: Conversation) -> [ChatMessage] {
        convo.messages.filter(messageMatches)
    }

    /// Chats shown in the sidebar: all of them, or those whose title or messages match the search.
    var filteredConversations: [Conversation] {
        guard isSearching else { return sortedConversations }
        let q = trimmedSearchQuery
        return sortedConversations.filter { $0.title.localizedCaseInsensitiveContains(q) || $0.messages.contains(where: messageMatches) }
    }

    var defaultModelName: String? {
        if !settings.defaultModel.isEmpty, models.contains(where: { $0.name == settings.defaultModel }) { return settings.defaultModel }
        return models.first?.name
    }

    var currentModelName: String? { selected?.model ?? defaultModelName }

    func modelInfo(_ name: String?) -> OllamaModelInfo? {
        guard let name else { return nil }
        return models.first { $0.name == name }
    }

    /// nil = unknown (older Ollama without capabilities), true/false otherwise.
    func modelSupportsVision(_ name: String?) -> Bool? {
        guard let name, let info = modelInfo(name), info.capabilities != nil else { return nil }
        return info.supportsVision
    }

    /// Installed models that can look at images.
    var visionModels: [OllamaModelInfo] { models.filter(\.supportsVision) }

    /// nil = unknown (older Ollama without capabilities), true/false otherwise.
    func modelSupportsTools(_ name: String) -> Bool? {
        if modelsWithoutTools.contains(name) { return false }
        return modelInfo(name)?.supportsTools
    }

    // MARK: - Lifecycle

    func bootstrap() async {
        conversations = store.loadAll()
        groups = store.loadGroups()
        let valid = Set(groups.map(\.id))
        for c in conversations where c.groupID != nil && !valid.contains(c.groupID!) {
            update(c.id) { $0.groupID = nil }
        }
        if conversations.isEmpty { newConversation() } else { selectedID = sortedConversations.first?.id }
        await refreshStatus()
        await refreshWebStatus()
    }

    // MARK: - Web status

    /// Probes the proxy or Tor so the sidebar shows whether the model's web requests can get out.
    func refreshWebStatus() async {
        guard settings.internetEnabled else { return }
        switch settings.proxyMode {
        case .tor:
            await tor.refresh(preferredPort: settings.torPort, controlPort: settings.torControlPort)
        case .http, .socks:
            if let ep = settings.webConfig.proxyEndpoint {
                proxyReachable = await TCPProbe.isOpen(host: ep.host, port: ep.port, timeout: 2)
            } else {
                proxyReachable = nil
            }
        case .direct:
            proxyReachable = nil
        }
    }

    /// Fetches check.torproject.org through the configured route and reports the exit IP.
    func testConnection() {
        guard !isCheckingConnection else { return }
        isCheckingConnection = true
        let config = settings.webConfig
        Task { [weak self] in
            guard let self else { return }
            do {
                let (ip, isTor) = try await WebTools.checkConnection(config: config)
                self.lastExitIP = ip
                if isTor {
                    self.connectionResult = "Through Tor, exit IP \(ip)."
                } else if config.proxyMode == .tor {
                    self.connectionResult = "Reached the internet, but NOT through a Tor exit (IP \(ip)). Check the Tor port."
                } else {
                    self.connectionResult = "Connected \(config.routeDescription). Public IP \(ip)."
                }
            } catch {
                self.lastExitIP = nil
                self.connectionResult = "Failed: \(error.localizedDescription)"
            }
            self.isCheckingConnection = false
        }
    }

    /// New Tor circuit (NEWNYM when a control port answers, else SIGHUP), then re-check the exit IP.
    func newTorCircuit() {
        Task { [weak self] in
            guard let self else { return }
            await self.tor.newCircuit(controlPassword: self.settings.torControlPassword)
            try? await Task.sleep(for: .seconds(2))
            self.testConnection()
        }
    }

    /// SIGHUP: reload tor's configuration and retire the circuits in use.
    func reloadTor() {
        Task { [weak self] in
            guard let self else { return }
            await self.tor.reload()
            try? await Task.sleep(for: .seconds(2))
            self.testConnection()
        }
    }

    func refreshStatus() async {
        do {
            let v = try await client.version()
            status = .connected(v)
            await refreshModels()
        } catch {
            status = .unreachable(error.localizedDescription)
            models = []
        }
    }

    func refreshModels() async {
        do {
            models = try await client.listModels()
            runningModels = (try? await client.runningModels()) ?? []
            let names = Set(models.map(\.name))
            modelStats = modelStats.filter { names.contains($0.key) }
            if settings.defaultModel.isEmpty, let first = models.first { settings.defaultModel = first.name }
        } catch {
            errorBanner = error.localizedDescription
        }
    }

    func startOllama() {
        isStartingOllama = true
        Task {
            // Prefer the Ollama.app if installed, otherwise run `ollama serve` in the background.
            let open = await ShellRunner.run(executable: "/usr/bin/open", arguments: ["-a", "Ollama"], cwd: NSHomeDirectory(), timeout: 15)
            if open.exitCode != 0 {
                _ = await ShellRunner.run(command: "nohup ollama serve >/dev/null 2>&1 &", cwd: NSHomeDirectory(), timeout: 10)
            }
            for _ in 0..<15 {
                try? await Task.sleep(for: .seconds(1))
                await refreshStatus()
                if status.isConnected { break }
            }
            isStartingOllama = false
        }
    }

    // MARK: - Conversations

    @discardableResult
    func newConversation(in groupID: UUID?? = nil) -> Conversation {
        var c = Conversation()
        c.model = defaultModelName
        if let cwd = selected?.workingDirectory { c.workingDirectory = cwd }
        // Explicit group if given, otherwise the group of the current chat.
        c.groupID = groupID ?? selected?.groupID
        conversations.insert(c, at: 0)
        selectedID = c.id
        store.save(c)
        return c
    }

    func deleteConversation(_ id: UUID) {
        if id == selectedID, isGenerating { stopGeneration() }
        conversations.removeAll { $0.id == id }
        store.delete(id)
        if selectedID == id { selectedID = sortedConversations.first?.id }
        if conversations.isEmpty { newConversation(in: .some(nil)) }
    }

    func renameConversation(_ id: UUID, title: String) {
        let t = title.trimmingCharacters(in: .whitespacesAndNewlines)
        update(id) {
            $0.title = t.isEmpty ? "New chat" : t
            $0.titleIsCustom = !t.isEmpty
        }
    }

    // MARK: - Groups

    var sortedGroups: [ChatGroup] {
        groups.sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    func group(_ id: UUID?) -> ChatGroup? {
        guard let id else { return nil }
        return groups.first { $0.id == id }
    }

    func conversations(in groupID: UUID?) -> [Conversation] {
        sortedConversations.filter { $0.groupID == groupID }
    }

    @discardableResult
    func createGroup(named name: String) -> ChatGroup? {
        let n = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !n.isEmpty else { return nil }
        if let existing = groups.first(where: { $0.name.localizedCaseInsensitiveCompare(n) == .orderedSame }) { return existing }
        let g = ChatGroup(name: n)
        groups.append(g)
        store.saveGroups(groups)
        return g
    }

    func renameGroup(_ id: UUID, name: String) {
        let n = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !n.isEmpty, let idx = groups.firstIndex(where: { $0.id == id }) else { return }
        groups[idx].name = n
        store.saveGroups(groups)
    }

    /// Removes the group; its chats move back to the top level.
    func deleteGroup(_ id: UUID) {
        groups.removeAll { $0.id == id }
        store.saveGroups(groups)
        for c in conversations where c.groupID == id { update(c.id) { $0.groupID = nil } }
    }

    func moveConversation(_ id: UUID, toGroup groupID: UUID?) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }), conversations[idx].groupID != groupID else { return }
        conversations[idx].groupID = groupID
        store.save(conversations[idx])
    }

    // MARK: - Automatic naming

    /// Asks the model for a short title once the first exchange is complete. Skipped when
    /// the user has renamed the chat; `force` regenerates even if a name exists.
    func generateTitle(for convoID: UUID, force: Bool = false) {
        guard let convo = conversation(convoID), !generatingTitleIDs.contains(convoID) else { return }
        guard force || (!convo.titleIsCustom && !convo.titleGenerated) else { return }
        guard let user = convo.messages.first(where: { $0.role == .user }),
              let reply = convo.messages.last(where: { $0.role == .assistant && !$0.content.isEmpty && !$0.isStreaming }),
              let modelName = convo.model ?? defaultModelName else { return }
        if force { update(convoID) { $0.titleIsCustom = false } }
        update(convoID) { $0.titleGenerated = true }
        generatingTitleIDs.insert(convoID)
        let client = self.client
        let think: Bool? = modelInfo(modelName)?.supportsThinking == true ? false : nil
        // Same num_ctx as normal chats, so Ollama reuses the loaded model instead of reloading it.
        let options: [String: Any] = ["temperature": 0.2, "num_predict": 32, "num_ctx": settings.contextLength]
        let prompt = """
        Conversation:

        User: \(String(user.apiContent.prefix(1500)))

        Assistant: \(String(reply.content.prefix(1500)))

        Title:
        """
        let messages: [[String: Any]] = [
            ["role": "system", "content": "You name chat conversations. Reply with only the title: two to five words, in the language of the user's message, no quotes, no trailing period, no explanation."],
            ["role": "user", "content": prompt],
        ]
        Task { [weak self] in
            let raw = (try? await client.chatOnce(model: modelName, messages: messages, options: options, think: think)) ?? ""
            guard let self else { return }
            self.generatingTitleIDs.remove(convoID)
            guard let title = Self.cleanTitle(raw), let current = self.conversation(convoID), !current.titleIsCustom else { return }
            self.update(convoID) { $0.title = title }
        }
    }

    static func cleanTitle(_ raw: String) -> String? {
        var t = raw.replacingOccurrences(of: "<think>[\\s\\S]*?</think>", with: "", options: .regularExpression)
        t = t.trimmingCharacters(in: .whitespacesAndNewlines)
        t = t.components(separatedBy: .newlines).first { !$0.trimmingCharacters(in: .whitespaces).isEmpty } ?? ""
        if let r = t.range(of: "^\\s*title\\s*:\\s*", options: [.regularExpression, .caseInsensitive]) { t.removeSubrange(r) }
        t = t.replacingOccurrences(of: "[*_`#]", with: "", options: .regularExpression)
        t = t.trimmingCharacters(in: CharacterSet(charactersIn: "\"'“”‘’«» .!"))
        t = t.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        guard t.count >= 2 else { return nil }
        return String(t.prefix(60))
    }

    func setModel(_ name: String) {
        guard let id = selectedID else { return }
        update(id) { $0.model = name }
        settings.defaultModel = name
    }

    func setWorkingDirectory(_ url: URL) {
        guard let id = selectedID else { return }
        update(id) { $0.workingDirectory = url.path }
    }

    func chooseWorkingDirectory() {
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        panel.prompt = "Use folder"
        panel.message = "Choose the working directory Roger should use for files and commands."
        if let cwd = selected?.workingDirectory { panel.directoryURL = URL(fileURLWithPath: cwd) }
        if panel.runModal() == .OK, let url = panel.url { setWorkingDirectory(url) }
    }

    func clearMessages() {
        guard let id = selectedID else { return }
        if isGenerating { stopGeneration() }
        update(id) { $0.messages = []; $0.title = "New chat" }
    }

    private func update(_ id: UUID, _ body: (inout Conversation) -> Void) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }) else { return }
        body(&conversations[idx])
        conversations[idx].updatedAt = Date()
        store.save(conversations[idx])
    }

    private func conversation(_ id: UUID) -> Conversation? {
        conversations.first { $0.id == id }
    }

    private func appendMessage(_ message: ChatMessage, to id: UUID) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }) else { return }
        conversations[idx].messages.append(message)
    }

    private func updateMessage(_ messageID: UUID, in id: UUID, _ body: (inout ChatMessage) -> Void) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }),
              let midx = conversations[idx].messages.firstIndex(where: { $0.id == messageID }) else { return }
        body(&conversations[idx].messages[midx])
    }

    private func updateToolCall(_ callID: UUID, message messageID: UUID, in id: UUID, _ body: (inout ToolCall) -> Void) {
        updateMessage(messageID, in: id) { msg in
            if let t = msg.toolCalls.firstIndex(where: { $0.id == callID }) { body(&msg.toolCalls[t]) }
        }
    }

    private func removeMessage(_ messageID: UUID, in id: UUID) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }) else { return }
        conversations[idx].messages.removeAll { $0.id == messageID }
    }

    private func persist(_ id: UUID) {
        guard let idx = conversations.firstIndex(where: { $0.id == id }) else { return }
        conversations[idx].updatedAt = Date()
        store.save(conversations[idx])
    }

    // MARK: - Sending

    func send(text: String, attachments: [Attachment]) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !isGenerating, !(trimmed.isEmpty && attachments.isEmpty) else { return }
        guard let convoID = selectedID, let convo = conversation(convoID) else { return }
        guard let modelName = convo.model ?? defaultModelName else {
            errorBanner = "No model available. Install one from the Models window."
            return
        }
        var message = ChatMessage(role: .user, content: trimmed, attachments: attachments)
        message.isStreaming = false
        appendMessage(message, to: convoID)
        if convo.messages.filter({ $0.role == .user }).isEmpty {
            let base = trimmed.isEmpty ? attachments.map(\.fileName).joined(separator: ", ") : trimmed
            let title = base.components(separatedBy: .newlines).first ?? base
            update(convoID) { $0.title = String(title.prefix(48)) }
        }
        persist(convoID)
        startGeneration(conversationID: convoID, model: modelName)
    }

    /// Removes the last assistant turn (and any tool messages after the last user message)
    /// and regenerates a fresh response to the same prompt.
    func regenerateLast() {
        guard !isGenerating, let convoID = selectedID, let convo = conversation(convoID),
              let modelName = convo.model ?? defaultModelName else { return }
        guard let lastUser = convo.messages.lastIndex(where: { $0.role == .user }) else { return }
        guard let idx = conversations.firstIndex(where: { $0.id == convoID }) else { return }
        conversations[idx].messages.removeSubrange((lastUser + 1)...)
        persist(convoID)
        startGeneration(conversationID: convoID, model: modelName)
    }

    /// Number of messages that would be discarded by editing and resending `messageID`.
    func messagesAfter(_ messageID: UUID) -> Int {
        guard let convo = selected, let idx = convo.messages.firstIndex(where: { $0.id == messageID }) else { return 0 }
        return convo.messages[(idx + 1)...].filter { $0.role == .user || $0.role == .assistant }.count
    }

    /// Replaces the text of an earlier user message, discards everything after it and
    /// asks the model again from that point. Attachments on the message are kept.
    func editAndResend(messageID: UUID, text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !isGenerating, let convoID = selectedID, let convo = conversation(convoID),
              let idx = conversations.firstIndex(where: { $0.id == convoID }),
              let midx = convo.messages.firstIndex(where: { $0.id == messageID }),
              convo.messages[midx].role == .user else { return }
        guard !(trimmed.isEmpty && convo.messages[midx].attachments.isEmpty) else { return }
        guard let modelName = convo.model ?? defaultModelName else {
            errorBanner = "No model available. Install one from the Models window."
            return
        }
        conversations[idx].messages.removeSubrange((midx + 1)...)
        conversations[idx].messages[midx].content = trimmed
        conversations[idx].messages[midx].editedAt = Date()
        if convo.messages.firstIndex(where: { $0.role == .user }) == midx, !trimmed.isEmpty {
            let title = trimmed.components(separatedBy: .newlines).first ?? trimmed
            conversations[idx].title = String(title.prefix(48))
        }
        persist(convoID)
        startGeneration(conversationID: convoID, model: modelName)
    }

    private func startGeneration(conversationID convoID: UUID, model modelName: String) {
        errorBanner = nil
        isGenerating = true
        generationTask = Task { [weak self] in
            guard let self else { return }
            await self.runAgentLoop(conversationID: convoID, model: modelName)
            self.isGenerating = false
            self.generationTask = nil
            self.pendingApprovalID = nil
            self.generateTitle(for: convoID)
        }
    }

    /// Stops the current reply but keeps whatever the model has produced so far.
    func stopGeneration() {
        generationTask?.cancel()
        if approvalContinuation != nil { resolveApproval(.deny) }
    }

    // MARK: - Approvals

    private func awaitApproval(for callID: UUID) async -> ApprovalDecision {
        await withCheckedContinuation { continuation in
            approvalContinuation = continuation
            pendingApprovalID = callID
        }
    }

    func resolveApproval(_ decision: ApprovalDecision) {
        pendingApprovalID = nil
        let c = approvalContinuation
        approvalContinuation = nil
        c?.resume(returning: decision)
    }

    // MARK: - Agent loop

    private func runAgentLoop(conversationID: UUID, model: String) async {
        let client = self.client
        var useTools = settings.toolsEnabled && modelSupportsTools(model) != false
        var iterations = 0
        let maxIterations = max(1, settings.maxToolIterations)

        while iterations < maxIterations {
            iterations += 1
            guard let convo = conversation(conversationID) else { return }
            let assistantID = UUID()
            appendMessage(ChatMessage(id: assistantID, role: .assistant, content: "", isStreaming: true, model: model), to: conversationID)

            let apiMessages = buildAPIMessages(for: convo, tools: useTools)
            let options: [String: Any] = ["temperature": settings.temperature, "num_ctx": settings.contextLength]
            var collected: [ToolCall] = []
            var stats: String?
            var receivedChunks = 0
            var reportedModel = false
            var rawContent = ""
            var apiThinking = ""
            let think: Bool? = (settings.reasoningMode == .off && modelInfo(model)?.supportsThinking == true) ? false : nil

            // Some models (older DeepSeek-R1 builds, for instance) put their reasoning in
            // <think> tags inside the content instead of Ollama's separate field. Keep both
            // kinds apart from the visible reply.
            func applyText() {
                let (inline, visible) = Self.splitInlineThinking(rawContent)
                let thinking = [apiThinking, inline ?? ""].filter { !$0.isEmpty }.joined(separator: "\n\n")
                updateMessage(assistantID, in: conversationID) {
                    $0.content = visible
                    $0.thinking = thinking.isEmpty ? nil : thinking
                }
            }

            do {
                let stream = client.chat(model: model, messages: apiMessages, tools: useTools ? ToolRegistry.definitions(internet: settings.internetEnabled) : nil, options: options, think: think)
                for try await chunk in stream {
                    if Task.isCancelled { break }
                    if !reportedModel, let name = chunk.model, !name.isEmpty {
                        reportedModel = true
                        if name != model { updateMessage(assistantID, in: conversationID) { $0.model = name } }
                    }
                    if let msg = chunk.message {
                        if let c = msg.content, !c.isEmpty {
                            receivedChunks += 1
                            rawContent += c
                            applyText()
                        }
                        if let t = msg.thinking, !t.isEmpty {
                            apiThinking += t
                            applyText()
                        }
                        if let calls = msg.toolCalls {
                            for raw in calls {
                                collected.append(ToolCall(name: raw.function.name, arguments: raw.function.arguments?.objectValue ?? [:], callID: raw.id))
                            }
                        }
                    }
                    if chunk.done == true {
                        updateMessage(assistantID, in: conversationID) {
                            $0.promptTokens = chunk.promptEvalCount
                            $0.completionTokens = chunk.evalCount
                        }
                        if let n = chunk.evalCount, let d = chunk.evalDuration, d > 0 {
                            let tps = Double(n) / (Double(d) / 1e9)
                            stats = String(format: "%d tokens · %.1f tok/s", n, tps)
                        }
                    }
                }
            } catch is CancellationError {
                finish(assistantID, in: conversationID, stats: stats, stopped: true, receivedChunks: receivedChunks)
                return
            } catch {
                if useTools, (error as? OllamaError)?.isToolsUnsupported == true {
                    modelsWithoutTools.insert(model)
                    useTools = false
                    removeMessage(assistantID, in: conversationID)
                    iterations -= 1
                    continue
                }
                updateMessage(assistantID, in: conversationID) {
                    $0.error = self.friendlyError(error, model: model)
                    $0.isStreaming = false
                }
                persist(conversationID)
                return
            }

            if Task.isCancelled {
                finish(assistantID, in: conversationID, stats: stats, stopped: true, receivedChunks: receivedChunks)
                return
            }

            if collected.isEmpty {
                finish(assistantID, in: conversationID, stats: stats)
                return
            }

            updateMessage(assistantID, in: conversationID) {
                $0.toolCalls = collected
                $0.isStreaming = false
                $0.stats = stats
            }

            let cwd = convo.workingDirectory
            for call in collected {
                if Task.isCancelled { break }
                guard let result = await execute(call, assistantID: assistantID, conversationID: conversationID, cwd: cwd) else { break }
                appendMessage(ChatMessage(role: .tool, content: result, toolName: call.name, toolCallID: call.callID), to: conversationID)
            }
            if Task.isCancelled {
                // Leave the calls that did run as they are; mark the rest so they don't
                // look like they are still waiting for something.
                updateMessage(assistantID, in: conversationID) { msg in
                    msg.stopped = true
                    for i in msg.toolCalls.indices where msg.toolCalls[i].status == .pending || msg.toolCalls[i].status == .running {
                        msg.toolCalls[i].status = .cancelled
                        msg.toolCalls[i].result = "Not run: generation was stopped."
                    }
                }
                persist(conversationID)
                return
            }
            persist(conversationID)
        }

        appendMessage(ChatMessage(role: .assistant, content: "I stopped after \(maxIterations) tool steps. Send another message if you want me to continue."), to: conversationID)
        persist(conversationID)
    }

    private func friendlyError(_ error: Error, model: String) -> String {
        if let e = error as? OllamaError, e.isVisionUnsupported {
            let alternatives = visionModels.map(\.name)
            let hint = alternatives.isEmpty
                ? "No installed model can look at images; pull one from the Models window (for example qwen2.5vl, gemma3 or llava)."
                : "Switch to \(alternatives.joined(separator: ", ")) or remove the image."
            return "\(model) can't look at images. \(hint)"
        }
        return error.localizedDescription
    }

    private func finish(_ assistantID: UUID, in conversationID: UUID, stats: String?, stopped: Bool = false, receivedChunks: Int = 0) {
        updateMessage(assistantID, in: conversationID) {
            $0.isStreaming = false
            $0.stopped = stopped
            if stopped {
                // Ollama only reports counts on the final chunk, which never arrives when
                // we cancel; each streamed chunk is roughly one token.
                $0.stats = receivedChunks > 0 ? "~\(receivedChunks) tokens before stop" : nil
            } else {
                $0.stats = stats
                if $0.content.isEmpty && $0.toolCalls.isEmpty && $0.error == nil {
                    if let t = $0.thinking, !t.isEmpty {
                        // The model put its whole answer in its reasoning and never wrote a
                        // reply. Show the reasoning as the answer, clearly labelled.
                        $0.content = t
                        $0.thinking = nil
                        $0.answeredInReasoning = true
                    } else {
                        $0.content = "*(no response)*"
                    }
                }
            }
        }
        persist(conversationID)
    }

    /// Separates a leading `<think>…</think>` block from the visible reply.
    static func splitInlineThinking(_ raw: String) -> (thinking: String?, content: String) {
        let open = "<think>", close = "</think>"
        let trimmed = raw.drop(while: { $0.isWhitespace || $0.isNewline })
        guard trimmed.hasPrefix(open) else {
            // While the first token is still arriving, don't flash "<thi" on screen.
            if !trimmed.isEmpty, open.hasPrefix(trimmed) { return (nil, "") }
            return (nil, raw)
        }
        let body = trimmed.dropFirst(open.count)
        if let end = body.range(of: close) {
            let thinking = String(body[..<end.lowerBound]).trimmingCharacters(in: .whitespacesAndNewlines)
            let content = String(body[end.upperBound...].drop(while: { $0.isWhitespace || $0.isNewline }))
            return (thinking.isEmpty ? nil : thinking, content)
        }
        let thinking = String(body).trimmingCharacters(in: .whitespacesAndNewlines)
        return (thinking.isEmpty ? nil : thinking, "")
    }

    /// Remembers an approval for the chat's working directory and lets the pending call run.
    func rememberApproval(_ scope: ApprovalScope, call: ToolCall, messageID: UUID) {
        guard let convoID = selectedID, let cwd = selected?.workingDirectory else { return }
        let directory = scope.isFolderScoped ? URL(fileURLWithPath: cwd).standardizedFileURL.path : ""
        let rule = approvals.add(scope, directory: directory)
        updateToolCall(call.id, message: messageID, in: convoID) { $0.approvedBy = rule.title }
        resolveApproval(.allow)
    }

    /// Runs one tool call. Returns nil when generation was stopped before the tool ran.
    private func execute(_ call: ToolCall, assistantID: UUID, conversationID: UUID, cwd: String) async -> String? {
        let isWeb = ToolRegistry.isWeb(call.name)
        let autoApproved: Bool
        if isWeb {
            autoApproved = !settings.askBeforeInternet
        } else {
            autoApproved = ToolRegistry.isCommand(call.name) ? settings.autoApproveCommands : settings.autoApproveFileEdits
        }
        let gated = ToolRegistry.requiresApproval(call.name) || isWeb
        var rememberedRule: ApprovalRule?
        if gated, !autoApproved, !allowAllThisSession {
            rememberedRule = approvals.rule(allowing: call, cwd: cwd)
        }
        if let rememberedRule {
            updateToolCall(call.id, message: assistantID, in: conversationID) { $0.approvedBy = rememberedRule.title }
        }
        let needsApproval = gated && !allowAllThisSession && !autoApproved && rememberedRule == nil

        if needsApproval {
            let decision = await awaitApproval(for: call.id)
            if Task.isCancelled {
                updateToolCall(call.id, message: assistantID, in: conversationID) { $0.status = .cancelled; $0.result = "Not run: generation was stopped." }
                return nil
            }
            switch decision {
            case .deny:
                let msg = "The user denied this action. Do not retry it; explain what you wanted to do and ask how to proceed."
                updateToolCall(call.id, message: assistantID, in: conversationID) { $0.status = .denied; $0.result = msg }
                return msg
            case .allowAll:
                allowAllThisSession = true
            case .allow:
                break
            }
        }

        updateToolCall(call.id, message: assistantID, in: conversationID) { $0.status = .running; $0.result = nil }
        if isWeb, settings.internetEnabled, settings.proxyMode == .tor { await tor.refresh(preferredPort: settings.torPort, controlPort: settings.torControlPort) }
        let web: WebConfig? = settings.internetEnabled ? settings.webConfig : nil
        let (ok, output) = await ToolExecutor.execute(call, cwd: cwd, loginShell: settings.useLoginShell, web: web) { [weak self] partial in
            self?.updateToolCall(call.id, message: assistantID, in: conversationID) {
                if $0.status == .running { $0.result = partial }
            }
        }
        updateToolCall(call.id, message: assistantID, in: conversationID) {
            $0.status = ok ? .done : .failed
            $0.result = output
        }
        toolRunCount += 1
        return output
    }

    // MARK: - Prompt building

    private func systemPrompt(for convo: Conversation, tools: Bool, trimmedMessages: Int = 0) -> String {
        let date = Date().formatted(date: .long, time: .omitted)
        var p = """
        You are Roger, a helpful coding assistant running locally on the user's Mac through Ollama. \
        You answer questions, write code, analyse bugs and help with the user's files.
        Today is \(date). The working directory is: \(convo.workingDirectory)
        Format answers in Markdown. Put code in fenced code blocks with a language tag. Be concise and precise. Always write your final answer as your visible response, never only inside your private reasoning.
        """
        if tools {
            p += """
            \n\nYou have tools to work on the local machine: read_file, write_file, edit_file, list_directory, search_files and run_command. \
            Use them when the user asks about files or wants changes made. Read a file before editing it, and prefer edit_file for small \
            changes over rewriting whole files. Paths may be relative to the working directory. run_command, write_file and edit_file \
            require the user's approval; if an action is denied, do not retry it. When you identify a fix for a file that already exists in the working directory, apply it with edit_file (or write_file for a new file) instead of only printing the corrected code. After using tools, summarise what you did and what you found.
            """
            if settings.internetEnabled {
                p += """
                \n\nYou also have internet access: web_search finds pages and fetch_url reads one (HTML, text or PDF). Use them for \
                anything recent, factual, or outside your training data, and to read documentation. Prefer one good search over \
                many; read the most relevant result before answering. Cite the URLs you relied on. Requests go \(settings.webConfig.routeDescription).
                """
            }
        } else {
            p += """
            \n\nWhen you suggest shell commands, put each in its own ```bash code block so the user can run it with one click. \
            When you propose file changes, show the full updated code in a code block and name the file.
            """
        }
        let extra = settings.customInstructions.trimmingCharacters(in: .whitespacesAndNewlines)
        if !extra.isEmpty { p += "\n\nAdditional instructions from the user:\n\(extra)" }
        if trimmedMessages > 0 {
            p += "\n\nThe \(trimmedMessages) earliest messages of this conversation were left out because they no longer fit in the context window. If the user refers to something you cannot see, say that it was trimmed rather than guessing."
        }
        return p
    }

    // MARK: - Context budget

    /// Effective context window for a model: the Settings value, capped by the model's
    /// own maximum when Roger knows it.
    func contextWindow(for modelName: String?) -> Int {
        let configured = settings.contextLength
        if let name = modelName, let max = modelStats[name]?.contextLength, max > 0 { return min(configured, max) }
        return configured
    }

    func contextPlan(for convo: Conversation) -> ContextPlan {
        let modelName = convo.model ?? defaultModelName
        let tools = settings.toolsEnabled && (modelName.map { modelSupportsTools($0) != false } ?? false)
        let fixed = TokenEstimator.tokens(forText: systemPrompt(for: convo, tools: tools)) + (tools ? TokenEstimator.toolDefinitionTokens(internet: settings.internetEnabled) : 0)
        return ContextPlan.plan(messages: convo.messages, fixedTokens: fixed, window: contextWindow(for: modelName), autoTrim: settings.autoTrimContext)
    }

    private func buildAPIMessages(for convo: Conversation, tools: Bool) -> [[String: Any]] {
        let plan = contextPlan(for: convo)
        // Never hand images to a model that cannot see them: Ollama rejects the whole request.
        let canSeeImages = modelSupportsVision(convo.model ?? defaultModelName) != false
        var out: [[String: Any]] = [["role": "system", "content": systemPrompt(for: convo, tools: tools, trimmedMessages: plan.trimmedCount)]]
        for m in convo.messages[plan.firstSentIndex...] {
            switch m.role {
            case .system:
                continue
            case .user:
                var d: [String: Any] = ["role": "user", "content": m.apiContent]
                let imageAttachments = m.attachments.filter(\.isImage)
                if !imageAttachments.isEmpty {
                    if canSeeImages {
                        d["images"] = imageAttachments.compactMap(\.imageBase64)
                    } else {
                        let names = imageAttachments.map(\.fileName).joined(separator: ", ")
                        d["content"] = (m.apiContent + "\n\n[The user attached an image (\(names)) that this text-only model cannot see. Say so if it matters.]").trimmingCharacters(in: .whitespacesAndNewlines)
                    }
                }
                out.append(d)
            case .assistant:
                if m.isStreaming || (m.content.isEmpty && m.toolCalls.isEmpty) { continue }
                var d: [String: Any] = ["role": "assistant", "content": m.content]
                if !m.toolCalls.isEmpty {
                    if tools {
                        d["tool_calls"] = m.toolCalls.map { call -> [String: Any] in
                            var t: [String: Any] = ["function": ["name": call.name, "arguments": call.arguments.mapValues(\.anyValue)]]
                            if let id = call.callID { t["id"] = id }
                            return t
                        }
                    } else {
                        let desc = m.toolCalls.map { "[Used tool \($0.name) with \($0.arguments.mapValues { $0.stringValue ?? "" })]" }.joined(separator: "\n")
                        d["content"] = (m.content + "\n" + desc).trimmingCharacters(in: .whitespacesAndNewlines)
                    }
                }
                out.append(d)
                // Calls that never ran (generation stopped) have no tool message of their
                // own; give the model a result anyway so every call is answered.
                for call in m.toolCalls where call.status == .cancelled {
                    let note = "[Not run: the user stopped generation before this tool call.]"
                    if tools {
                        var d: [String: Any] = ["role": "tool", "content": note, "tool_name": call.name]
                        if let id = call.callID { d["tool_call_id"] = id }
                        out.append(d)
                    } else {
                        out.append(["role": "user", "content": "[Result of \(call.name)]\n\(note)"])
                    }
                }
            case .tool:
                if tools {
                    var d: [String: Any] = ["role": "tool", "content": m.content, "tool_name": m.toolName ?? ""]
                    if let id = m.toolCallID { d["tool_call_id"] = id }
                    out.append(d)
                } else {
                    out.append(["role": "user", "content": "[Result of \(m.toolName ?? "tool")]\n\(m.content)"])
                }
            }
        }
        return out
    }

    // MARK: - Model management

    func pullModel(_ rawName: String) {
        let name = rawName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !name.isEmpty, !isPulling else { return }
        isPulling = true
        pullingName = name
        pullError = nil
        pullProgress = nil
        pullTask = Task {
            do {
                for try await progress in client.pull(name) {
                    if let e = progress.error { throw OllamaError.server(e) }
                    pullProgress = progress
                }
                await refreshModels()
                if selected?.model == nil { setModel(name) }
            } catch is CancellationError {
                pullError = "Download of \(name) cancelled."
            } catch {
                pullError = Task.isCancelled ? "Download of \(name) cancelled." : error.localizedDescription
            }
            isPulling = false
            pullProgress = nil
            pullTask = nil
        }
    }

    /// Stops an in-progress pull. Ollama aborts the download when the connection closes;
    /// already-downloaded layers stay cached so a later pull resumes quickly.
    func cancelPull() {
        pullTask?.cancel()
    }

    func deleteModel(_ name: String) async {
        do {
            try await client.deleteModel(name)
            await refreshModels()
            for c in conversations where c.model == name {
                update(c.id) { $0.model = nil }
            }
            if settings.defaultModel == name { settings.defaultModel = models.first?.name ?? "" }
        } catch {
            errorBanner = error.localizedDescription
        }
    }

    var totalModelBytes: Int64 { models.reduce(0) { $0 + ($1.size ?? 0) } }

    func loadStats(for name: String) async {
        guard modelStats[name] == nil, !loadingStats.contains(name) else { return }
        loadingStats.insert(name)
        defer { loadingStats.remove(name) }
        if let show = try? await client.showModel(name) {
            modelStats[name] = ModelStats(show: show)
        }
    }

    func loadAllStats() async {
        await withTaskGroup(of: Void.self) { group in
            for m in models { group.addTask { await self.loadStats(for: m.name) } }
        }
    }

    func unloadModel(_ name: String) async {
        try? await client.unloadModel(name)
        await refreshModels()
    }
}
